### ISSUE TITLE
Options for setting global loading/error image

### ISSUE THREAD

**Issue by black-black-cat** [jofftiquez/v-img-fallback#1]
Hey buddy! @jofftiquez 

Could you add some options to set loading or error image for every binding image.

Such as:

```javascript
 Vue.use('VImgFallback', {
    loading: 'path/to/loading.png',
    error: 'path/to/error.png'
}
```

**Comment by jofftiquez** [comment]
@black-black-cat nice idea! I will do this, this weekend. Thanks!
