### ISSUE TITLE
loading override not working

### ISSUE THREAD

**Issue by dvergeer** [jofftiquez/v-img-fallback#3]
Hello. Create plugin. I noticed an issue when I add a loading override image.

This is my setting.

Vue.use(VImgFallback, {
  loading: '/static/img/loading.gif',
  error: '/static/img/no_picture.svg'
}) 

The error image override does work perfectly.

In the plugin code I get the message that loading is not declared.

![image](https://user-images.githubusercontent.com/2749455/45026247-026da080-b03e-11e8-8875-730a8206dfd4.png)

Regards,

Dennis

**Comment by YaoaY** [comment]
because variable 'loading' has been re-defined:
`var loading = _ref.loading,`
`var loading = defaultLoading;`

the option value of loading was lost 😢

**Comment by jofftiquez** [comment]
@YaoaY Im kindof busy with other stuff right now. Can you do a PR? Thank you.

**Comment by jofftiquez** [comment]
Upgrade to `v0.1.5`
